POST http://localhost:4000/api/v1/auth/sign-up HTTP/1.1
Content-Type: application/json

{
    "name":"Test",
    "userName":"test",
    "email":"email@mail.com",
    "password":"1234",
    "role":"admin"
}

###

POST http://localhost:4000/api/v1/admin/add-product HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoidGVzdCIsIl9pZCI6IjYxYTA0MzM2ZTI2MDM2MmE2MGEyYzkwMiIsInJvbGUiOiJhZG1pbiIsInRva2VuVmVyc2lvbiI6MCwiaWF0IjoxNjM3ODkyOTE4LCJleHAiOjE2Mzc5NzkzMTh9.7E3QMv4xPPPmFCAoGotDF2suDcxUJKuMkAodNEu1hQ4

{
    "name":"Product1",
    "description1":"description",
    "description2":"Long description about product 1",
    "price":15000,
    "amount":4
}